apiVersion: apps/v1
kind: Deployment
metadata:
  name: colourapp
  labels:
    app: colourapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: colourapp
  template:
    metadata:
      labels:
        app: colourapp
    spec:
      containers:
      - name: colourapp
        image: {{ .Values.image.repository | quote }}
        ports:
        - containerPort: 80
        env:
        - name: COLOUR
          value: Blue
      imagePullPolicy: {{ .Values.image.pullPolicy }}