# Default values for colour-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: "davevans/colourapp:1.4"
  pullPolicy: IfNotPresent  